### ISSUE TITLE
Possible Class Library For Zipper

### ISSUE THREAD

**Issue by musictopia2** [TimCorey/VSZipper#1]
Have you thought of the idea of a class library as a starting point.  One possibility can be an external class library which I can actually create.  In that case, you just go to add nuget packages.  Then reference it.   Since I am very good with interfaces, I can easily create a system where interfaces are done.  You can implement the interfaces.  Then when ready, it will use that and do its job.   Can even do mocking for zipping so a process can be done where it pretends like its zipping it its really not zipping for test purposes.  If you would be interested in that then I can create a nuget package and explain how to use it so creating this project would be much easier.
In this case, then the class library does not care what UI is used (console, WPF, Windows Forms) or even blazor.

**Comment by TimCorey** [comment]
The goal here isn't to create a library that we can call from code. The goal is to create a working application that we can easily use. I'm not intending to create a NuGet package out of this.
