### ISSUE TITLE
Possible .net tool

### ISSUE THREAD

**Issue by musictopia2** [TimCorey/VSZipper#2]
I saw a video that shows its possible to create a .net tool.
Would you consider eventually doing as .net tool.
The way it seems to work is nuget shows the commands.
If a person does globally, then its like another program running on your computer.
But what happens is you enter the first command which represents your program.
Then you decide what arguments you put to it.
Then your program can do its job.  As a dotnet tool, then somebody can create a batch program where if they have several visual studio projects to zip up, then several can run instead of doing one at a time.  There can even be an option for a pre build process that before building the process, it can run the program and put in one of the arguments.  Then it can zip up and put to whatever folder they want to specify.

**Comment by TimCorey** [comment]
Interesting suggestion, but that's beyond what I'm looking to do with this app at this time.
